// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function DuplicateTab(arg1) {
  return window['go']['main']['App']['DuplicateTab'](arg1);
}

export function ExportAllTabs(arg1) {
  return window['go']['main']['App']['ExportAllTabs'](arg1);
}

export function GetLastError() {
  return window['go']['main']['App']['GetLastError']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetStorageDir() {
  return window['go']['main']['App']['GetStorageDir']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTabFilePath(arg1) {
  return window['go']['main']['App']['GetTabFilePath'](arg1);
}

export function NewTab() {
  return window['go']['main']['App']['NewTab']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PinTab(arg1, arg2) {
  return window['go']['main']['App']['PinTab'](arg1, arg2);
}

export function RenameTab(arg1, arg2) {
  return window['go']['main']['App']['RenameTab'](arg1, arg2);
}

export function ReorderTabs(arg1, arg2) {
  return window['go']['main']['App']['ReorderTabs'](arg1, arg2);
}

export function SaveCurrentFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCurrentFile'](arg1, arg2);
}

export function SaveFileAs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2, arg3);
}

export function SaveTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTab'](arg1, arg2, arg3);
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}

export function ShareCancel() {
  return window['go']['main']['App']['ShareCancel']();
}

export function ShareReceive(arg1) {
  return window['go']['main']['App']['ShareReceive'](arg1);
}

export function ShareSend(arg1) {
  return window['go']['main']['App']['ShareSend'](arg1);
}
